POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "name": "ddd",
  "password": "ddd",
  "email": "dkdeeeekdkek@naekke.come",
  "phoneNumber": "92918182i3"
}

###

POST http://localhost:8080/auth/login
Content-Type: application/x-www-form-urlencoded

username=dddd&password=dddd
