
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "username": "ssssss",
  "password": "dddfwee",
  "email": "dkdeeeekdkek@naekke.come",
  "phoneNumber": "92918182i3"
}

###

POST http://localhost:8080/auth/login
Content-Type: application/x-www-form-urlencoded

username=dddf&password=dddf

###


# @no-redirect
POST http://localhost:8080/auth/login
Content-Type:application/json

{
  "username": "ssssss",
  "password": "dddfwee"
}

###

POST http://localhost:8080/board/user/writePost
Content-Type: multipart/form-data


{
  "title": "dddf",
  "content": "dddf"

}


###

GET http://localhost:8080/board/posts/list?page=1&size=5

###
GET http://localhost:8080/user/information
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzc3Nzc3MiLCJhdXRoIjoiVVNFUiIsImV4cCI6MTY5MzM5OTA3N30.sNSP5Nm8uQJyWfoYE31GcC1Nf0KW8EGSum09p8HO-_Y